version: '3'

services:
  standalone-chrome:
    image: 'selenium/standalone-chrome:3.14.0-helium'
    ports:
      - '4444'
    # Necessary due to some issues with chrome in docker.  See https://github.com/SeleniumHQ/docker-selenium#running-the-images
    volumes:
      - '/dev/shm:/dev/shm'
    # Necessary to lock down screen sizes for our screen shot comparisons.
    environment:
      TZ: 'America/Chicago'

  dev:
    image: cerner/terra-node-dev:1
    ports:
      - 8080:8080
    depends_on:
      - standalone-chrome
    volumes:
      - .:/opt/module

  test-ci:
    build: ./
    image: "${DOCKER_IMAGE}-test:${TAG:-latest}"
    depends_on:
      - standalone-chrome
